version: '3.4'

services:
  mssql_db:
    image: ${DOCKER_REGISTRY-}mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  api:
    image: ${DOCKER_REGISTRY-}mcr.microsoft.com/dotnet/aspnet
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: mIRC.Web/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - mssql_db